package util;

import util.MailDTO;

public class MailContent {
	
	//	전자계약 업체서명요청 메일 내용.
	public static String signReqContent(MailDTO mailDTO){
		StringBuffer mailbuffer = new StringBuffer();
		
		mailbuffer.append(" \n <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">")
		.append(" \n <html lang=\"ko\">")
		.append(" \n <head>")
		.append(" \n <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">")
		.append(" \n <meta http-equiv=\"cache-control\" content=\"no-cache, must-revalidate\">")
		.append(" \n <meta http-equiv=\"pragma\" content=\"no-cache\">")
		.append(" \n <meta http-equiv=\"imagetoolbar\" content=\"no\">")
		.append(" \n <link href=\"https://www.csbill.co.kr/common/css/style.css\" rel=\"stylesheet\" type=\"text/css\">")
		.append(" \n </head>")
		.append(" \n <body>")
		.append(" \n  <table  width='700' border='0' cellpadding='0' >")
		.append(" \n <tr>")
		.append(" \n <td>본 메일은 <font color='red'>발신전용</font>으로 회신이 되지 않습니다. 관련 문의는 <font color='red'>담당자 이메일</font>을 이용하시기 바랍니다.</td> ")
		.append(" \n </tr>")
		.append(" \n </table>")
		.append(" \n <table width=\"700\" border=\"0\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"3d474e\">")
		.append(" \n <tr>")
		.append(" \n 	<td valign=\"top\" bgcolor=\"#FFFFFF\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">")
		.append(" \n 		<tr>")
		.append(" \n 			<td colspan=\"3\"><img src=\"https://www.csbill.co.kr/images/mail/formmail_img01.gif\" /></td>")
		.append(" \n 		</tr>")
		.append(" \n 		<tr>")
		//.append(" \n 			<td width=\"13\" valign=\"top\"><img src=\"https://www.csbill.co.kr/common/images/mail/img03.jpg\" width=\"13\" height=\"243\" /></td>")
		.append(" \n 			<td width=\"100%\" valign=\"top\" class=\"pd_ud\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">")
		.append(" \n 				<tr>")
		.append(" \n 					<td valign=\"top\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"e2e3e3\" style=\"margin-bottom:30px;\">")
		.append(" \n 						<tr>")
		.append(" \n 							<td bgcolor=\"#FFFFFF\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">")
		.append(" \n 								<tr>")
		.append(" \n 									<td height=\"34\" bgcolor=\"e8e8e8\" class=\"pl10\"><table>")
		.append(" \n 										<tr>")
		.append(" \n 											<td width=\"10\"><img src=\"https://www.csbill.co.kr/images/mail/blue_ic.gif\" /></td>")
		.append(" \n 											<td class=\"blue01 B\"><b>To. "+mailDTO.getBuye_Orgn_Name()+" ["+mailDTO.getBuye_Pers_Name()+"]</b>님</td>")
		.append(" \n 										</tr>")
		.append(" \n				 					</table></td>")
		.append(" \n 								</tr>")
		.append(" \n 								<tr>")
		.append(" \n 									<td valign=\"top\" bgcolor=\"f3f3f3\" class=\"p15\">안녕하세요? <b>"+mailDTO.getSupp_Orgn_Name()+"</b>입니다.<br>")
		.append(" \n									CSBill을 통해 작성된 전자문서의 서명을 요청 하오니, 전자문서를 확인하신 후, 처리하여 주시기 바랍니다.<br>")
		.append(" \n 									\"전자문서 확인하기\" 버튼을 이용하여 확인하시기 바랍니다.<br>")	
		.append(" \n 									</td>")
		.append(" \n 								</tr>")
		.append(" \n 							</table></td>")			
		.append(" \n 						</tr>")			
		.append(" \n					</table>")			
		.append(" \n 					<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:5px 0 20px 0\">")
		.append(" \n						<tr>")
		.append(" \n 							<td height=\"2\" bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 						</tr>")			
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">계약명</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\">"+mailDTO.getCont_Nm()+"</td>")
		.append(" \n 						</tr>")		
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">계약이행기간</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\">"+mailDTO.getCont_Date_From()+" ~ " +mailDTO.getCont_Date_To()+"</td>")
		.append(" \n 						</tr>")	
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">계약일자</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\">"+mailDTO.getCont_Date()+"</td>")
		.append(" \n 						</tr>")			
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">담당자명 / 연락처</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\">" + mailDTO.getSupp_Pers_Name() + " /  "+mailDTO.getSupp_Pers_Tele()+"</td>")
		.append(" \n 						</tr>")
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">이메일</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\"><a href='mailto:"+mailDTO.getSupp_Pers_Mail()+"' style='color:blue'><u>"+mailDTO.getSupp_Pers_Mail()+"</u></a></td>")
		.append(" \n 						</tr>");
	// 업체서명요청 또는 업체서명진행중일 경우엔 아래 문구 보여줌. 2008.11.19 PCH
//	if(Utils.checkNull(mailDTO.getCont_Proc_Stat()).equals("200") || Utils.checkNull(mailDTO.getCont_Proc_Stat()).equals("300")){
//		mailbuffer.append(" \n						<tr>")
//		.append(" \n							<td colspan=\"2\"><table>")
//		.append(" \n								<tr>")
//		.append(" \n									<td>계약 체결 후 서울보증보험증권(계약,하자이행)을 해당기업에 제출하시려면<br>CSBill(서울보증보험대리점)에서 신속하게 보험증권 발급 및 무료 발송해 드립니다.<br>문의 : 1566-5950)</td>")
//		.append(" \n								</tr>")
//		.append(" \n							</table></td>")
//		.append(" \n						</tr>");		
//	}	
		mailbuffer.append(" \n				<tr>")
		.append(" \n 							<td height=\"1\" bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 						</tr>")	
		.append(" \n					</table>")
		.append(" \n					<table>")
		.append(" \n 						<tr>")
		.append(" \n 							<td height=\"20\"></td>")
		.append(" \n 						</tr>")
		.append(" \n 					</table>")
		.append(" \n					<table width=\"100%\">")
		.append(" \n						<tr>")
        .append(" \n        					<td align=\"center\"><a href=\"https://www.csbill.co.kr/loginMailView.do?cont_Numb="+mailDTO.getCont_Numb()+"&cont_Chng_Numb="+mailDTO.getCont_Chng_Numb()+"&mailGb=C\" target=\"_blank\"><img src=\"http://www.csbill.co.kr/images/mail/btn_go3.gif\" style=\"cursor:hand\"></a></td>")
        .append(" \n      					</tr>")
        .append(" \n						<tr>")
        .append(" \n        					<td align=\"center\"><a href=\"https://www.csbill.co.kr\" target=\"_blank\">이미지 링크가 되지 않을 경우 여기를 클릭해주세요.</a></td>")
        .append(" \n      					</tr>")
        .append(" \n    				</table></td>")
		.append(" \n 					<td width=\"20\">&nbsp;</td>")
		.append(" \n 					<td width=\"180\" valign=\"top\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"97a7bf\">")
		.append(" \n						<tr>")
		.append(" \n							<td align=\"center\" valign=\"top\" bgcolor=\"#FFFFFF\"><p><img src=\"https://www.csbill.co.kr/images/mail/img04_1.gif\" /></p>")
		.append(" \n							<img src=\"https://www.csbill.co.kr/images/mail/img05_1.gif\" /><table width=\"162\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"e2e3e3\" style=\"margin-bottom:20px\">")
		.append(" \n								<tr>")
		.append(" \n									<td bgcolor=\"f7f8f9\" style=\"padding:5px\"><table width=\"100%\">")
		.append(" \n										<tr>")
		.append(" \n 											<td width=\"5\" valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">버튼을 클릭하여 CSBILL에 로그인 합니다. </td>")
		.append(" \n										</tr>")			
		.append(" \n										<tr>")
		.append(" \n 											<td valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">보안 프로그램 설치안내  화면이 나타날 경우에는  반드시 “예” 를 선택하여  설치하신 후  로그인합니다.</td>")
		.append(" \n										</tr>")
		.append(" \n										<tr>")
		.append(" \n 											<td valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">\"전자계약\" -> \"계약서 조회\"</td>")
		.append(" \n										</tr>")
		.append(" \n										<tr>")
		.append(" \n 											<td valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">갑, 을 서명이 완료된 \"계약완료\"상태의 전자계약서에 대해 인쇄, 다운로드 등의 작업을 진행할 수 있습니다.</td>")
		.append(" \n										</tr>")
		.append(" \n									</td>")
		.append(" \n								</tr>")
		.append(" \n 							</table>")
        .append(" \n							</table></td>")
        .append(" \n						</tr>")
        .append(" \n					</table></td>")
        .append(" \n				</tr>")
        .append(" \n			</table></td>")
        //.append(" \n			<td width=\"13\" valign=\"top\"><img src=\"https://www.csbill.co.kr/common/images/mail/img03.jpg\" width=\"13\" height=\"243\" /></td>")
        .append(" \n		</tr>")
        .append(" \n		<tr>")
        .append(" \n			<td colspan=\"3\"><img src=\"https://www.csbill.co.kr/images/mail/formmail_img02.gif\" /></td>")
        .append(" \n		</tr>")
        .append(" \n		<tr>")
        .append(" \n			<td colspan=\"3\"><img src=\"https://www.csbill.co.kr/images/mail/formmail_img03.gif\" /></td>")
        .append(" \n		</tr>")
        .append(" \n	</table></td>")				
        .append(" \n</tr>")
        .append(" \n</table>")
        .append(" \n</body>")
        .append(" \n</html>");		

		return mailbuffer.toString();
	}
	
//	전자계약 업체서명요청 메일 내용.
	public static String signAjReqContent(MailDTO mailDTO){
		StringBuffer mailbuffer = new StringBuffer();
		
		mailbuffer.append(" \n <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">")
		.append(" \n <html lang=\"ko\">")
		.append(" \n <head>")
		.append(" \n <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">")
		.append(" \n <meta http-equiv=\"cache-control\" content=\"no-cache, must-revalidate\">")
		.append(" \n <meta http-equiv=\"pragma\" content=\"no-cache\">")
		.append(" \n <meta http-equiv=\"imagetoolbar\" content=\"no\">")
		.append(" \n <link href=\"https://www.csbill.co.kr/common/css/style.css\" rel=\"stylesheet\" type=\"text/css\">")
		.append(" \n </head>")
		.append(" \n <body>")
		.append(" \n  <table  width='700' border='0' cellpadding='0' >")
		.append(" \n <tr>")
		.append(" \n <td>본 메일은 <font color='red'>발신전용</font>으로 회신이 되지 않습니다. 관련 문의는 <font color='red'>담당자 이메일</font>을 이용하시기 바랍니다.</td> ")
		.append(" \n </tr>")
		.append(" \n </table>")
		.append(" \n <table width=\"700\" border=\"0\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"3d474e\">")
		.append(" \n <tr>")
		.append(" \n 	<td valign=\"top\" bgcolor=\"#FFFFFF\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">")
		.append(" \n 		<tr>")
		.append(" \n 			<td colspan=\"3\"><img src=\"https://www.csbill.co.kr/images/mail/formmail_img01.gif\" /></td>")
		.append(" \n 		</tr>")
		.append(" \n 		<tr>")
		.append(" \n 			<td width=\"100%\" valign=\"top\" class=\"pd_ud\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">")
		.append(" \n 				<tr>")
		.append(" \n 					<td valign=\"top\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"e2e3e3\" style=\"margin-bottom:30px;\">")
		.append(" \n 						<tr>")
		.append(" \n 							<td bgcolor=\"#FFFFFF\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">")
		.append(" \n 								<tr>")
		.append(" \n 									<td height=\"34\" bgcolor=\"e8e8e8\" class=\"pl10\"><table>")
		.append(" \n 										<tr>")
		.append(" \n 											<td width=\"10\"><img src=\"https://www.csbill.co.kr/images/mail/blue_ic.gif\" /></td>")
		.append(" \n 											<td class=\"blue01 B\"><b>To. "+mailDTO.getBuye_Orgn_Name()+" ["+mailDTO.getBuye_Pers_Name()+"]</b>님</td>")
		.append(" \n 										</tr>")
		.append(" \n				 					</table></td>")
		.append(" \n 								</tr>")
		.append(" \n 								<tr>")
		.append(" \n 									<td valign=\"top\" bgcolor=\"f3f3f3\" class=\"p15\">안녕하세요? <b>"+mailDTO.getSupp_Orgn_Name()+"</b>입니다.<br>")
		.append(" \n									CSBill을 통해 작성된 전자문서의 서명을 요청 하오니, 전자문서를 확인하신 후, 처리하여 주시기 바랍니다.<br>")
		.append(" \n 									\"전자문서 확인하기\" 버튼을 이용하여 확인하시기 바랍니다.<br>")	
		.append(" \n 									</td>")
		.append(" \n 								</tr>")
		.append(" \n 								<tr>")
		.append(" \n 									<td valign=\"top\" bgcolor=\"f3f3f3\" class=\"p15\"><b>씨에스빌 로그인 계정</b><br>")
		.append(" \n									아이디 : AJN + 사업자번호<br/>")	
		.append(" \n									비밀번호 : 핸드폰 끝 4자리 + 사업자번호 끝 3자리")	
		.append(" \n 									</td>")
		.append(" \n 								</tr>")
		.append(" \n 							</table></td>")			
		.append(" \n 						</tr>")			
		.append(" \n					</table>")			
		.append(" \n 					<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:5px 0 20px 0\">")
		.append(" \n						<tr>")
		.append(" \n 							<td height=\"2\" bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 						</tr>")			
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">계약명</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\">"+mailDTO.getCont_Nm()+"</td>")
		.append(" \n 						</tr>")		
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">계약이행기간</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\">"+mailDTO.getCont_Date_From()+" ~ " +mailDTO.getCont_Date_To()+"</td>")
		.append(" \n 						</tr>")	
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">계약일자</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\">"+mailDTO.getCont_Date()+"</td>")
		.append(" \n 						</tr>")			
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">담당 이메일</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\"><a href='mailto:"+mailDTO.getSupp_Pers_Mail()+"' style='color:blue'><u>"+mailDTO.getSupp_Pers_Mail()+"</u></a></td>")
		.append(" \n 						</tr>");
		mailbuffer.append(" \n				<tr>")
		.append(" \n 							<td height=\"1\" bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 						</tr>")	
		.append(" \n					</table>")
		.append(" \n					<table>")
		.append(" \n 						<tr>")
		.append(" \n 							<td height=\"20\"></td>")
		.append(" \n 						</tr>")
		.append(" \n 					</table>")
		.append(" \n					<table width=\"100%\">")
		.append(" \n						<tr>")
        .append(" \n        					<td align=\"center\"><a href=\"https://www.csbill.co.kr/loginMailView.do?cont_Numb="+mailDTO.getCont_Numb()+"&cont_Chng_Numb="+mailDTO.getCont_Chng_Numb()+"&mailGb=C\" target=\"_blank\"><img src=\"http://www.csbill.co.kr/images/mail/btn_go3.gif\" style=\"cursor:hand\"></a></td>")
        .append(" \n      					</tr>")
        .append(" \n						<tr>")
        .append(" \n        					<td align=\"center\"><a href=\"https://www.csbill.co.kr\" target=\"_blank\">이미지 링크가 되지 않을 경우 여기를 클릭해주세요.</a></td>")
        .append(" \n      					</tr>")
        .append(" \n    				</table></td>")
		.append(" \n 					<td width=\"20\">&nbsp;</td>")
		.append(" \n 					<td width=\"180\" valign=\"top\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"97a7bf\">")
		.append(" \n						<tr>")
		.append(" \n							<td align=\"center\" valign=\"top\" bgcolor=\"#FFFFFF\"><p><img src=\"https://www.csbill.co.kr/images/mail/img04_1.gif\" /></p>")
		.append(" \n							<img src=\"https://www.csbill.co.kr/images/mail/img05_1.gif\" /><table width=\"162\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"e2e3e3\" style=\"margin-bottom:20px\">")
		.append(" \n								<tr>")
		.append(" \n									<td bgcolor=\"f7f8f9\" style=\"padding:5px\"><table width=\"100%\">")
		.append(" \n										<tr>")
		.append(" \n 											<td width=\"5\" valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">버튼을 클릭하여 CSBILL에 로그인 합니다. </td>")
		.append(" \n										</tr>")			
		.append(" \n										<tr>")
		.append(" \n 											<td valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">보안 프로그램 설치안내  화면이 나타날 경우에는  반드시 “예” 를 선택하여  설치하신 후  로그인합니다.</td>")
		.append(" \n										</tr>")
		.append(" \n										<tr>")
		.append(" \n 											<td valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">\"전자계약\" -> \"계약서 조회\"</td>")
		.append(" \n										</tr>")
		.append(" \n										<tr>")
		.append(" \n 											<td valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">갑, 을 서명이 완료된 \"계약완료\"상태의 전자계약서에 대해 인쇄, 다운로드 등의 작업을 진행할 수 있습니다.</td>")
		.append(" \n										</tr>")
		.append(" \n									</td>")
		.append(" \n								</tr>")
		.append(" \n 							</table>")
        .append(" \n							</table></td>")
        .append(" \n						</tr>")
        .append(" \n					</table></td>")
        .append(" \n				</tr>")
        .append(" \n			</table></td>")
        //.append(" \n			<td width=\"13\" valign=\"top\"><img src=\"https://www.csbill.co.kr/common/images/mail/img03.jpg\" width=\"13\" height=\"243\" /></td>")
        .append(" \n		</tr>")
        .append(" \n		<tr>")
        .append(" \n			<td colspan=\"3\"><img src=\"https://www.csbill.co.kr/images/mail/formmail_img02.gif\" /></td>")
        .append(" \n		</tr>")
        .append(" \n		<tr>")
        .append(" \n			<td colspan=\"3\"><img src=\"https://www.csbill.co.kr/images/mail/formmail_img03.gif\" /></td>")
        .append(" \n		</tr>")
        .append(" \n	</table></td>")				
        .append(" \n</tr>")
        .append(" \n</table>")
        .append(" \n</body>")
        .append(" \n</html>");		

		return mailbuffer.toString();
	}
	
	/**
	 * 잔액확인서 업체서명요청 메일 내용.
	 * 동원 잔액확인서 전용
	 * @param mailDTO
	 * @return
	 */
	public static String signReqContent2(MailDTO mailDTO){
		StringBuffer mailbuffer = new StringBuffer();
		
		mailbuffer.append(" \n <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">")
		.append(" \n <html lang=\"ko\">")
		.append(" \n <head>")
		.append(" \n <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">")
		.append(" \n <meta http-equiv=\"cache-control\" content=\"no-cache, must-revalidate\">")
		.append(" \n <meta http-equiv=\"pragma\" content=\"no-cache\">")
		.append(" \n <meta http-equiv=\"imagetoolbar\" content=\"no\">")
		.append(" \n <link href=\"https://www.csbill.co.kr/common/css/style.css\" rel=\"stylesheet\" type=\"text/css\">")
		.append(" \n </head>")
		.append(" \n <body>")
		.append(" \n  <table  width='700' border='0' cellpadding='0' >")
		.append(" \n <tr>")
		.append(" \n <td>본 메일은 <font color='red'>발신전용</font>으로 회신이 되지 않습니다. 관련 문의는 <font color='red'>담당자 이메일</font>을 이용하시기 바랍니다.</td> ")
		.append(" \n </tr>")
		.append(" \n </table>")
		.append(" \n <table width=\"700\" border=\"0\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"3d474e\">")
		.append(" \n <tr>")
		.append(" \n 	<td valign=\"top\" bgcolor=\"#FFFFFF\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">")
		.append(" \n 		<tr>")
		.append(" \n 			<td colspan=\"3\"><img src=\"https://www.csbill.co.kr/images/mail/formmail_img01.gif\" /></td>")
		.append(" \n 		</tr>")
		.append(" \n 		<tr>")
		//.append(" \n 			<td width=\"13\" valign=\"top\"><img src=\"https://www.csbill.co.kr/common/images/mail/img03.jpg\" width=\"13\" height=\"243\" /></td>")
		.append(" \n 			<td width=\"100%\" valign=\"top\" class=\"pd_ud\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">")
		.append(" \n 				<tr>")
		.append(" \n 					<td valign=\"top\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"e2e3e3\" style=\"margin-bottom:30px;\">")
		.append(" \n 						<tr>")
		.append(" \n 							<td bgcolor=\"#FFFFFF\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">")
		.append(" \n 								<tr>")
		.append(" \n 									<td height=\"34\" bgcolor=\"e8e8e8\" class=\"pl10\"><table>")
		.append(" \n 										<tr>")
		.append(" \n 											<td width=\"10\"><img src=\"https://www.csbill.co.kr/images/mail/blue_ic.gif\" /></td>")
		.append(" \n 											<td class=\"blue01 B\"><b>To. "+mailDTO.getBuye_Orgn_Name()+" ["+mailDTO.getBuye_Pers_Name()+"]</b>님</td>")
		.append(" \n 										</tr>")
		.append(" \n				 					</table></td>")
		.append(" \n 								</tr>")
		.append(" \n 								<tr>")
		.append(" \n 									<td valign=\"top\" bgcolor=\"f3f3f3\" class=\"p15\">안녕하세요? <b>"+mailDTO.getSupp_Orgn_Name()+"</b>입니다.<br>")
		.append(" \n									CSBill을 통해 작성된 잔액확인서의 서명을 요청 하오니, 잔액확인서를 확인하신 후, 전자서명 바랍니다.<br>")
		.append(" \n 									\"잔액확인서 확인하기\" 버튼을 이용하여 확인하시기 바랍니다.<br>")	
		.append(" \n 									</td>")
		.append(" \n 								</tr>")
		.append(" \n 							</table></td>")			
		.append(" \n 						</tr>")			
		.append(" \n					</table>")			
		.append(" \n 					<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:5px 0 20px 0\">")
		.append(" \n						<tr>")
		.append(" \n 							<td height=\"2\" bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 						</tr>")			
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">잔액명</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\">"+mailDTO.getCont_Nm()+"</td>")
		.append(" \n 						</tr>")		
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">잔액(기준)일</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\">"+mailDTO.getCont_Date()+"</td>")
		.append(" \n 						</tr>")			
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">발송 업체</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\">"+mailDTO.getSupp_Orgn_Name()+"</td>")
		.append(" \n 						</tr>")	
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">담당 이메일</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\"><a href='mailto:"+mailDTO.getSupp_Pers_Mail()+"' style='color:blue'><u>"+mailDTO.getSupp_Pers_Mail()+"</u></a></td>")
		.append(" \n 						</tr>");
		mailbuffer.append(" \n				<tr>")
		.append(" \n 							<td height=\"1\" bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 						</tr>")	
		.append(" \n					</table>")
		.append(" \n					<table>")
		.append(" \n 						<tr>")
		.append(" \n 							<td height=\"20\"></td>")
		.append(" \n 						</tr>")
		.append(" \n 					</table>")
		.append(" \n					<table width=\"100%\">")
		.append(" \n						<tr>")
        .append(" \n        					<td align=\"center\"><a href=\"https://www.csbill.co.kr/loginMailView.do?cont_Numb="+mailDTO.getCont_Numb()+"&cont_Chng_Numb="+mailDTO.getCont_Chng_Numb()+"&mailGb=bond\" target=\"_blank\"><img src=\"https://www.csbill.co.kr/images/mail/btn_go3_1.gif\" style=\"cursor:hand\"></a></td>")
//        .append(" \n        					<td align=\"center\"><a href=\"http://172.16.6.64:8081/main/login\" target=\"_blank\"><img src=\"https://www.csbill.co.kr/images/mail/btn_go3_1.gif\" style=\"cursor:hand\"></a></td>")
//        .append(" \n        					<td align=\"center\"><a href=\"http://bond.csbill.co.kr/ssoLoginSave.do?loginGb=login&cu_Id="+ mailDTO.getBuye_Pers_Id() +"\" target=\"_blank\"><img src=\"https://www.csbill.co.kr/images/mail/btn_go3_1.gif\" style=\"cursor:hand\"></a></td>")
        .append(" \n      					</tr>")
        .append(" \n						<tr>")
        .append(" \n        					<td align=\"center\"><a href=\"https://www.csbill.co.kr/loginMailView.do?cont_Numb="+mailDTO.getCont_Numb()+"&cont_Chng_Numb="+mailDTO.getCont_Chng_Numb()+"&mailGb=bond\" target=\"_blank\">이미지 링크가 되지 않을 경우 여기를 클릭해주세요.</a></td>")
//        .append(" \n        					<td align=\"center\"><a href=\"http://172.16.6.64:8081/main/login\" target=\"_blank\">이미지 링크가 되지 않을 경우 여기를 클릭해주세요.</a></td>")
//        .append(" \n        					<td align=\"center\"><a href=\"http://bond.csbill.co.kr/ssoLoginSave.do?loginGb=login&cu_Id="+ mailDTO.getBuye_Pers_Id() +"\" target=\"_blank\">이미지 링크가 되지 않을 경우 여기를 클릭해주세요.</a></td>")
        .append(" \n      					</tr>")
        .append(" \n    				</table></td>")
		.append(" \n 					<td width=\"20\">&nbsp;</td>")
		.append(" \n 					<td width=\"180\" valign=\"top\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"97a7bf\">")
		.append(" \n						<tr>")
		.append(" \n							<td align=\"center\" valign=\"top\" bgcolor=\"#FFFFFF\"><p><img src=\"https://www.csbill.co.kr/images/mail/img04_1.gif\" /></p>")
		.append(" \n							<img src=\"https://www.csbill.co.kr/images/mail/img05_1.gif\" /><table width=\"162\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"e2e3e3\" style=\"margin-bottom:20px\">")
		.append(" \n								<tr>")
		.append(" \n									<td bgcolor=\"f7f8f9\" style=\"padding:5px\"><table width=\"100%\">")
		.append(" \n										<tr>")
		.append(" \n 											<td width=\"5\" valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">버튼을 클릭하여 CSBILL에 로그인 합니다. </td>")
		.append(" \n										</tr>")			
		.append(" \n										<tr>")
		.append(" \n 											<td valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">보안 프로그램 설치안내  화면이 나타날 경우에는  반드시 “예” 를 선택하여  설치하신 후  로그인합니다.</td>")
		.append(" \n										</tr>")
		.append(" \n										<tr>")
		.append(" \n 											<td valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">\"전자계약\" -> \"채권잔액확인서 조회\"</td>")
		.append(" \n										</tr>")
		.append(" \n										<tr>")
		.append(" \n 											<td valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">\"잔액확인서 서명\"상태에서 출력 및 다운로드 가능하십니다.</td>")
		.append(" \n										</tr>")
		.append(" \n									</td>")
		.append(" \n								</tr>")
		.append(" \n 							</table>")
        .append(" \n							</table></td>")
        .append(" \n						</tr>")
        .append(" \n					</table></td>")
        .append(" \n				</tr>")
        .append(" \n			</table></td>")
        .append(" \n		</tr>")
        .append(" \n		<tr>")
        .append(" \n			<td colspan=\"3\"><img src=\"https://www.csbill.co.kr/images/mail/formmail_img02.gif\" /></td>")
        .append(" \n		</tr>")
        .append(" \n		<tr>")
        .append(" \n			<td colspan=\"3\"><img src=\"https://www.csbill.co.kr/images/mail/formmail_img03.gif\" /></td>")
        .append(" \n		</tr>")
        .append(" \n	</table></td>")				
        .append(" \n</tr>")
        .append(" \n</table>")
        .append(" \n</body>")
        .append(" \n</html>");		

		return mailbuffer.toString();
	}
	
	//	확인서 업체서명요청 메일 내용.
	public static String signReqContent3(MailDTO mailDTO){
		StringBuffer mailbuffer = new StringBuffer();
		
		mailbuffer.append(" \n <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">")
		.append(" \n <html lang=\"ko\">")
		.append(" \n <head>")
		.append(" \n <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">")
		.append(" \n <meta http-equiv=\"cache-control\" content=\"no-cache, must-revalidate\">")
		.append(" \n <meta http-equiv=\"pragma\" content=\"no-cache\">")
		.append(" \n <meta http-equiv=\"imagetoolbar\" content=\"no\">")
		.append(" \n <link href=\"https://www.csbill.co.kr/common/css/style.css\" rel=\"stylesheet\" type=\"text/css\">")
		.append(" \n </head>")
		.append(" \n <body>")
		.append(" \n  <table  width='700' border='0' cellpadding='0' >")
		.append(" \n <tr>")
		.append(" \n <td>본 메일은 <font color='red'>발신전용</font>으로 회신이 되지 않습니다. 관련 문의는 <font color='red'>담당자 이메일</font>을 이용하시기 바랍니다.</td> ")
		.append(" \n </tr>")
		.append(" \n </table>")
		.append(" \n <table width=\"700\" border=\"0\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"3d474e\">")
		.append(" \n <tr>")
		.append(" \n 	<td valign=\"top\" bgcolor=\"#FFFFFF\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">")
		.append(" \n 		<tr>")
		.append(" \n 			<td colspan=\"3\"><img src=\"https://www.csbill.co.kr/images/mail/formmail_img01.gif\" /></td>")
		.append(" \n 		</tr>")
		.append(" \n 		<tr>")
		//.append(" \n 			<td width=\"13\" valign=\"top\"><img src=\"https://www.csbill.co.kr/common/images/mail/img03.jpg\" width=\"13\" height=\"243\" /></td>")
		.append(" \n 			<td width=\"100%\" valign=\"top\" class=\"pd_ud\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">")
		.append(" \n 				<tr>")
		.append(" \n 					<td valign=\"top\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"e2e3e3\" style=\"margin-bottom:30px;\">")
		.append(" \n 						<tr>")
		.append(" \n 							<td bgcolor=\"#FFFFFF\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">")
		.append(" \n 								<tr>")
		.append(" \n 									<td height=\"34\" bgcolor=\"e8e8e8\" class=\"pl10\"><table>")
		.append(" \n 										<tr>")
		.append(" \n 											<td width=\"10\"><img src=\"https://www.csbill.co.kr/images/mail/blue_ic.gif\" /></td>")
		.append(" \n 											<td class=\"blue01 B\"><b>To. "+mailDTO.getBuye_Orgn_Name()+" ["+mailDTO.getBuye_Pers_Name()+"]</b>님</td>")
		.append(" \n 										</tr>")
		.append(" \n				 					</table></td>")
		.append(" \n 								</tr>")
		.append(" \n 								<tr>")
		.append(" \n 									<td valign=\"top\" bgcolor=\"f3f3f3\" class=\"p15\">안녕하세요? <b>"+mailDTO.getSupp_Orgn_Name()+"</b>입니다.<br>")
		.append(" \n									CSBill을 통해 작성된 전자확인서의 서명을 요청 하오니, 전자확인서를 확인하신 후, 처리하여 주시기 바랍니다.<br>")
		.append(" \n 									\"전자문서 확인하기\" 버튼을 이용하여 확인하시기 바랍니다.<br>")	
		.append(" \n 									</td>")
		.append(" \n 								</tr>")
		.append(" \n 							</table></td>")			
		.append(" \n 						</tr>")			
		.append(" \n					</table>")			
		.append(" \n 					<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:5px 0 20px 0\">")
		.append(" \n						<tr>")
		.append(" \n 							<td height=\"2\" bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 						</tr>")			
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">확인서명</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\">"+mailDTO.getCont_Nm()+"</td>")
		.append(" \n 						</tr>")		
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">확인일자</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\">"+mailDTO.getCont_Date()+"</td>")
		.append(" \n 						</tr>")			
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">담당자명 / 연락처</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\">" + mailDTO.getSupp_Pers_Name() + " /  "+mailDTO.getSupp_Pers_Tele()+"</td>")
		.append(" \n 						</tr>")
		.append(" \n						<tr>")
		.append(" \n							<td width=\"20%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b blue01 B line2_r\">이메일</td>")
		.append(" \n							<td width=\"80%\" align=\"center\" class=\"line2_b line2_r\"><a href='mailto:"+mailDTO.getSupp_Pers_Mail()+"' style='color:blue'><u>"+mailDTO.getSupp_Pers_Mail()+"</u></a></td>")
		.append(" \n 						</tr>");
	// 업체서명요청 또는 업체서명진행중일 경우엔 아래 문구 보여줌. 2008.11.19 PCH
//	if(Utils.checkNull(mailDTO.getCont_Proc_Stat()).equals("200") || Utils.checkNull(mailDTO.getCont_Proc_Stat()).equals("300")){
//		mailbuffer.append(" \n						<tr>")
//		.append(" \n							<td colspan=\"2\"><table>")
//		.append(" \n								<tr>")
//		.append(" \n									<td>계약 체결 후 서울보증보험증권(계약,하자이행)을 해당기업에 제출하시려면<br>CSBill(서울보증보험대리점)에서 신속하게 보험증권 발급 및 무료 발송해 드립니다.<br>문의 : 1566-5950)</td>")
//		.append(" \n								</tr>")
//		.append(" \n							</table></td>")
//		.append(" \n						</tr>");		
//	}	
		mailbuffer.append(" \n				<tr>")
		.append(" \n 							<td height=\"1\" bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 							<td bgcolor=\"4b79a4\"></td>")
		.append(" \n 						</tr>")	
		.append(" \n					</table>")
		.append(" \n					<table>")
		.append(" \n 						<tr>")
		.append(" \n 							<td height=\"20\"></td>")
		.append(" \n 						</tr>")
		.append(" \n 					</table>")
		.append(" \n					<table width=\"100%\">")
		.append(" \n						<tr>")
        .append(" \n        					<td align=\"center\"><a href=\"https://www.csbill.co.kr/loginMailView.do?cont_Numb="+mailDTO.getCont_Numb()+"&cont_Chng_Numb="+mailDTO.getCont_Chng_Numb()+"&mailGb=C\" target=\"_blank\"><img src=\"http://www.csbill.co.kr/images/mail/btn_go3.gif\" style=\"cursor:hand\"></a></td>")
        .append(" \n      					</tr>")
        .append(" \n						<tr>")
        .append(" \n        					<td align=\"center\"><a href=\"https://www.csbill.co.kr\" target=\"_blank\">이미지 링크가 되지 않을 경우 여기를 클릭해주세요.</a></td>")
        .append(" \n      					</tr>")
        .append(" \n    				</table></td>")
		.append(" \n 					<td width=\"20\">&nbsp;</td>")
		.append(" \n 					<td width=\"180\" valign=\"top\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"97a7bf\">")
		.append(" \n						<tr>")
		.append(" \n							<td align=\"center\" valign=\"top\" bgcolor=\"#FFFFFF\"><p><img src=\"https://www.csbill.co.kr/images/mail/img04_1.gif\" /></p>")
		.append(" \n							<img src=\"https://www.csbill.co.kr/images/mail/img05_1.gif\" /><table width=\"162\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"e2e3e3\" style=\"margin-bottom:20px\">")
		.append(" \n								<tr>")
		.append(" \n									<td bgcolor=\"f7f8f9\" style=\"padding:5px\"><table width=\"100%\">")
		.append(" \n										<tr>")
		.append(" \n 											<td width=\"5\" valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">버튼을 클릭하여 CSBILL에 로그인 합니다. </td>")
		.append(" \n										</tr>")			
		.append(" \n										<tr>")
		.append(" \n 											<td valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">보안 프로그램 설치안내  화면이 나타날 경우에는  반드시 “예” 를 선택하여  설치하신 후  로그인합니다.</td>")
		.append(" \n										</tr>")
		.append(" \n										<tr>")
		.append(" \n 											<td valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">\"전자계약\" -> \"계약서 조회\" -> \"확인서 조회\"</td>")
		.append(" \n										</tr>")
		.append(" \n										<tr>")
		.append(" \n 											<td valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">을 서명이 완료된 \"서명완료\"상태의 전자확인서에 대해 인쇄, 다운로드 등의 작업을 진행할 수 있습니다.</td>")
		.append(" \n										</tr>")
		.append(" \n									</td>")
		.append(" \n								</tr>")
		.append(" \n 							</table>")
        .append(" \n							</table></td>")
        .append(" \n						</tr>")
        .append(" \n					</table></td>")
        .append(" \n				</tr>")
        .append(" \n			</table></td>")
        //.append(" \n			<td width=\"13\" valign=\"top\"><img src=\"https://www.csbill.co.kr/common/images/mail/img03.jpg\" width=\"13\" height=\"243\" /></td>")
        .append(" \n		</tr>")
        .append(" \n		<tr>")
        .append(" \n			<td colspan=\"3\"><img src=\"https://www.csbill.co.kr/images/mail/formmail_img02.gif\" /></td>")
        .append(" \n		</tr>")
        .append(" \n		<tr>")
        .append(" \n			<td colspan=\"3\"><img src=\"https://www.csbill.co.kr/images/mail/formmail_img03.gif\" /></td>")
        .append(" \n		</tr>")
        .append(" \n	</table></td>")				
        .append(" \n</tr>")
        .append(" \n</table>")
        .append(" \n</body>")
        .append(" \n</html>");		

		return mailbuffer.toString();
	}
	
	//	계약해지 메일 내용.
	public static String terminReqContent(MailDTO mailDTO){
		StringBuffer mailbuffer = new StringBuffer();
		
		mailbuffer.append(" \n <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">")
		.append(" \n <html lang=\"ko\">")
		.append(" \n <head>")
		.append(" \n <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">")
		.append(" \n <meta http-equiv=\"cache-control\" content=\"no-cache, must-revalidate\">")
		.append(" \n <meta http-equiv=\"pragma\" content=\"no-cache\">")
		.append(" \n <meta http-equiv=\"imagetoolbar\" content=\"no\">")
		.append(" \n <link href=\"https://www.csbill.co.kr/common/css/style.css\" rel=\"stylesheet\" type=\"text/css\">")
		.append(" \n </head>")
		.append(" \n <body>")
		.append(" \n  <table  width='700' border='0' cellpadding='0' >")
		.append(" \n <tr>")
		.append(" \n <td>본 메일은 <font color='red'>발신전용</font>으로 회신이 되지 않습니다. 관련 문의는 <font color='red'>담당자 이메일</font>을 이용하시기 바랍니다.</td> ")
		.append(" \n </tr>")
		.append(" \n </table>")
		.append(" \n <table width=\"700\" border=\"0\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"3d474e\">")
		.append(" \n <tr>")
		.append(" \n 	<td valign=\"top\" bgcolor=\"#FFFFFF\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">")
		.append(" \n 		<tr>")
		.append(" \n 			<td colspan=\"3\"><img src=\"https://www.csbill.co.kr/images/mail/formmail_img01.gif\" /></td>")
		.append(" \n 		</tr>")
		.append(" \n 		<tr>")
		//.append(" \n 			<td width=\"13\" valign=\"top\"><img src=\"https://www.csbill.co.kr/common/images/mail/img03.jpg\" width=\"13\" height=\"243\" /></td>")
		.append(" \n 			<td width=\"100%\" valign=\"top\" class=\"pd_ud\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">")
		.append(" \n 				<tr>")
		.append(" \n 					<td valign=\"top\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"e2e3e3\" style=\"margin-bottom:30px;\">")
		.append(" \n 						<tr>")
		.append(" \n 							<td bgcolor=\"#FFFFFF\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\">")
		.append(" \n 								<tr>")
		.append(" \n 									<td height=\"34\" bgcolor=\"e8e8e8\" class=\"pl10\"><table>")
		.append(" \n 										<tr>")
		.append(" \n 											<td width=\"10\"><img src=\"https://www.csbill.co.kr/images/mail/blue_ic.gif\" /></td>")
		.append(" \n 											<td class=\"blue01 B\"><b>To. "+mailDTO.getBuye_Orgn_Name()+" ["+mailDTO.getBuye_Pers_Name()+"]</b>님</td>")
		.append(" \n 										</tr>")
		.append(" \n				 					</table></td>")
		.append(" \n 								</tr>")
		.append(" \n 								<tr>")
		.append(" \n 									<td valign=\"top\" bgcolor=\"f3f3f3\" class=\"p15\">안녕하세요? <b>"+mailDTO.getSupp_Orgn_Name()+"</b>입니다.<br>")
		.append(" \n									CSBill을 통해 계약완료된 전자계약서의 <b>계약해지 요청</b>을 하오니, 전자계약서를 확인하신 후 처리하여 주시기 바랍니다.<br>")
		.append(" \n 										<b>'전자계약서 확인하기'</b> 버튼을 이용하여 확인하시기 바랍니다.<br>")			
		.append(" \n 									</td>")
		.append(" \n 								</tr>")
		.append(" \n 							</table></td>")			
		.append(" \n 						</tr>")			
		.append(" \n					</table>")	
		.append(" \n					<table>")
		.append(" \n						<tr>")
		.append(" \n							<td height=\"10\"></td>")
		.append(" \n						</tr>")
		.append(" \n 					</table>")
		.append(" \n 					<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin:5px 0 20px 0\" frame=\"void\"> ")
		.append(" \n						<tr>")
		.append(" \n							<td height=\"2\" bgcolor=\"4b79a4\"></td> ")
		.append(" \n							<td height=\"2\" bgcolor=\"4b79a4\"></td> ")
		.append(" \n						</tr>")
		.append(" \n						<tr>")
		.append(" \n 							<td width=\30%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b line2_r\">계약명 </td>")
		.append(" \n 							<td align=\"center\" class=\"line2_b line2_r\" height=\"30\">"+mailDTO.getCont_Nm()+"</td> ")
		.append(" \n						</tr>")
//		.append(" \n						<tr>")
//		.append(" \n 							<td width=\30%\" height=\"30\" align=\"center\" bgcolor=\"edf4fc\" class=\"line2_b line2_r\">해지사유 </td>")
//		.append(" \n 							<td class=\"line2_b line2_r\" align=\"center\" >"+mailDTO.getCont_Reje_Text()+"</td> ")
//		.append(" \n 						</tr> ")
		.append(" \n						<tr>")
		.append(" \n							<td height=\"1\" bgcolor=\"4b79a4\"></td> ")
		.append(" \n							<td height=\"1\" bgcolor=\"4b79a4\"></td> ")
		.append(" \n						</tr>")
		.append(" \n					</table>")	
		.append(" \n					<table>")
		.append(" \n						<tr>")
		.append(" \n							<td height=\"20\"></td>")
		.append(" \n						</tr>")
		.append(" \n 					</table>")
		.append(" \n					<table width=100%>")
		.append(" \n						<tr>")
        .append(" \n        					<td align=\"center\"><a href=\"https://www.csbill.co.kr/loginMailView.do?cont_Numb="+mailDTO.getCont_Numb()+"&cont_Chng_Numb="+mailDTO.getCont_Chng_Numb()+"&mailGb=C\" target=\"_blank\"><img src=\"http://www.csbill.co.kr/images/mail/btn_go3.gif\" style=\"cursor:hand\"></a></td>")
        .append(" \n      					</tr>")
        .append(" \n    				</table></td>")
		.append(" \n 					<td width=\"20\">&nbsp;</td>")
		.append(" \n 					<td width=\"180\" valign=\"top\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"2\" bgcolor=\"97a7bf\">")
		.append(" \n						<tr>")
		.append(" \n							<td align=\"center\" valign=\"top\" bgcolor=\"#FFFFFF\"><p><img src=\"https://www.csbill.co.kr/images/mail/img04_1.gif\" /></p>")
		.append(" \n							<img src=\"https://www.csbill.co.kr/images/mail/img05_1.gif\" /><table width=\"162\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"e2e3e3\" style=\"margin-bottom:20px\">")
		.append(" \n								<tr>")
		.append(" \n									<td bgcolor=\"f7f8f9\" style=\"padding:5px\"><table width=\"100%\">")
		.append(" \n										<tr>")
		.append(" \n 											<td width=\"5\" valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">버튼을 클릭하여 CSBILL에 로그인 합니다. </td>")
		.append(" \n										</tr>")			
		.append(" \n										<tr>")
		.append(" \n 											<td valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">보안 프로그램 설치안내  화면이 나타날 경우에는  반드시 “예” 를 선택하여  설치하신 후  로그인합니다.</td>")
		.append(" \n										</tr>")
		.append(" \n										<tr>")
		.append(" \n 											<td valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">\"전자계약\" -> \"계약서 조회\"</td>")
		.append(" \n										</tr>")
		.append(" \n										<tr>")
		.append(" \n 											<td valign=\"top\">-</td>")
		.append(" \n											<td align=\"left\">갑, 을 서명이 완료된 \"계약완료\"상태의 전자계약서에 대해 인쇄, 다운로드 등의 작업을 진행할 수 있습니다.</td>")
		.append(" \n										</tr>")
		.append(" \n									</td>")
		.append(" \n								</tr>")
		.append(" \n							</table>")
		.append(" \n							</table></td>")
		.append(" \n						</tr>")
		.append(" \n					</table></td>")
		.append(" \n				</tr>")
		.append(" \n			</table></td>")
		//.append(" \n			<td width=\"13\" valign=\"top\"><img src=\"https://www.csbill.co.kr/common/images/mail/img03.jpg\" width=\"13\" height=\"243\" /></td>")
		.append(" \n		</tr>")
        .append(" \n		<tr>")
        .append(" \n			<td colspan=\"3\"><img src=\"https://www.csbill.co.kr/images/mail/formmail_img02.gif\" /></td>")
        .append(" \n		</tr>")
		.append(" \n		<tr>")
		.append(" \n			<td colspan=\"3\"><img src=\"https://www.csbill.co.kr/images/mail/formmail_img03.gif\" /></td>")
		.append(" \n		</tr>")
		.append(" \n		</table></td>")		
		.append(" \n	</tr>")
		.append(" \n</table>")			
		.append(" \n </body> ")
		.append(" \n </html> ");
		return mailbuffer.toString();
	}

}
